FROM php:8.3-cli

RUN docker-php-ext-install pdo_mysql

WORKDIR /var/www/html
COPY . .

RUN mkdir -p storage/uploads \
    && chmod -R 775 storage

ENV PORT=80

CMD ["sh", "-c", "php database/migrate.php && php -S 0.0.0.0:${PORT} router.php"]
